# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 05:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radar', '0002_auto_20170830_0506'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['weight'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='companycontact',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='industry',
            options={'verbose_name_plural': 'Industries'},
        ),
        migrations.AlterModelOptions(
            name='lead',
            options={'ordering': ['-created_at']},
        ),
    ]
