# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 05:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radar', '0003_auto_20170830_0513'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['name'], 'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='leadstatus',
            options={'verbose_name_plural': 'Lead Status'},
        ),
    ]
