# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radar', '0004_auto_20170830_0515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='opportunity',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lead',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lead',
            name='tags',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='radar.Tag'),
        ),
    ]
