# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radar', '0005_auto_20170830_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='location',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
